README.md

rather than absolute see https://help.github.com/articles/markdown-basics/#links which will also prevent page reload

docs(Readme): use relative hash linking

---

docs/API.md

In general I think the whole sentence needs a bit rephrasing. But first wanted to check with you guys.

docs(api.md): small typo

---

docs/API.md

Hi @Hotell as promise here are some docs typo corrections

docs(example): fix assert in ViewChild and ContentChild examples

---

src/core/directives/util/util.ts

fix(core/directives): Ensure watchers are functions (#69)

---

manual_typings/globals.d.ts

fix(manual_typings): Add boolean type to expensiveChecks (#72)

---

playground/app/components/todo-app.component.ts
playground/app/components/todo-item.component.ts
playground/ng-metadata.legacy.d.ts
src/facade/async.ts

Hi @Hotell as you asked in #66 I review your Event Emitter code
I made some changes to make it fully typed plus I added the EventHandler interface to enable type check even on "consumer side" components that handle the events emitted from child comp, see updated playground example for a possible use-case.
Sorry for the delay, but hope this is still in time to be accepted.

Event emitter typed

---

core.ts
docs/API.md
playground/app/components/todo-app.component.ts
playground/app/components/todo-app.html
playground/app/components/todo-item.component.ts
playground/app/components/todo-item.html
playground/ng-metadata.legacy.d.ts
src/core/directives/util/util.ts
src/facade/async.ts
src/facade/facade.ts
test/facade/async.spec.ts
test/index.ts

implements `EventEmitter` functionality like angular 2 does
- beware it is not a real Rx Subject, just abstraction
cc @dmorosinotto

Event emitter

---

docs/API.md

Complete bootstrap docs for strictDi according to changes in ngMetadata v1.6.0

docs (API/bootstrap): complete bootstrap docs for strictDi

---

docs/DESIGN-PATTERNS.md

Update TS sample code to be aligned with current ngMetadata version, expeccially provide method to register directive, service, etc... in angular

docs (DESIGN-PATTERNS): update TS code to current version

---

docs/API.md
manual_typings/globals.d.ts
playground/app/components/lifecycle/do-check-parent.component.html
playground/app/components/lifecycle/do-check.component.ts
playground/app/components/lifecycle/index.ts
playground/app/components/lifecycle/on-changes-parent.component.html
playground/app/components/lifecycle/on-changes.component.ts
playground/app/components/tester/tester.component.ts
playground/app/components/todo-app.html
playground/app/index.ts
playground/app/main.ts
playground/ng-metadata.legacy.d.ts
playground/style.css
src/core/directives/directive_provider.ts
src/core/directives/util/util.ts
src/core/linker.ts
src/core/linker/directive_lifecycle_interfaces.ts
src/core/linker/directive_lifecycles_reflector.ts
test/core/linker/directive_lifecycles_reflector.spec.ts

back ports [DoCheck](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html#!#docheck) to angular 1

DoCheck lifecycle

---

docs/API.md
docs/DESIGN-PATTERNS.md
router-deprecated.ts
src/core/directives/constants.ts
src/core/directives/directive_provider.ts
src/core/directives/metadata_directives.ts
src/router-deprecated/index.ts
src/router-deprecated/instructions.ts
src/router-deprecated/interfaces.ts
src/router-deprecated/route_definition.ts
src/router-deprecated/route_registry.ts
src/router-deprecated/router.ts
test/core/directives/directive_provider.spec.ts

Component router support

---

package.json
playground/app/todo/add-todo.component.ts
playground/app/todo/todo-app.html
playground/app/todo/todo-item.component.ts
playground/index.html
playground/ng-metadata.legacy.d.ts
src/core/directives/binding/binding_factory.ts
src/core/directives/controller/controller_factory.ts
src/facade/async.ts
test/core/directives/binding/binding_factory.spec.ts
test/facade/async.spec.ts
typings.json

Rx integration + real EventEmitter

---

package.json
playground/app/app.component.html
playground/app/app.component.ts
playground/app/components/attribute-directive/attribute-directive-example.component.ts
playground/app/components/attribute-directive/highlight.directive.ts
playground/app/todo/todo-app.html
playground/app/todo/todo-item.component.ts
src/core/di/provider.ts
src/core/di/provider_util.ts
src/core/di/reflective_provider.ts
src/core/directives/binding/binding_factory.ts
src/core/directives/binding/binding_parser.ts
src/core/directives/controller/controller_factory.ts
src/core/directives/directives_utils.ts
src/core/util/bundler.ts
test/core/di/reflective_provider.spec.ts
test/core/directives/binding/binding_factory.spec.ts
test/core/directives/binding/binding_parser.spec.ts

Binding type by template

---

src/core/reflection/platform_reflection_capabilities.ts
src/core/reflection/reflection_capabilities.ts
src/core/reflection/reflector.ts
src/core/util/bundler.ts
src/facade/lang.ts
src/platform/browser.ts
src/platform/browser_utils.ts
src/upgrade/upgrade.ts
src/upgrade/upgrade_adapter.ts
test/index.ts
test/upgrade/upgrade_adapter.spec.ts
upgrade.ts

feat(upgrade): Helper functions for hybrid apps

---

docs/recipes/ng-upgrade.md
upgrade.ts

Fixed: `
ERROR in ./~/ng-metadata/upgrade.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./src/upgrade/upgrade_adapter.ts in node_modules/ng-metadata
@ ./~/ng-metadata/upgrade.js 2:27-70
`

fixed doc typo + upgrade import.

---

src/common/directives/ng_form.ts

fix(core/directives/ng_form): add $name property

---

playground/app/app.component.ts
playground/app/app.module.ts
playground/app/components/async-example/async-example.component.ts
playground/app/components/async-example/async-example.module.ts
playground/app/components/attribute-directive/attribute-directive-example.component.ts
playground/app/components/attribute-directive/attribute-directive.module.ts
playground/app/index.ts
playground/app/main.ts
playground/app/todo/todo-app.component.ts
playground/app/todo/todo.module.ts
playground/ng-metadata.legacy.d.ts

pls just take quick look if I defined NgModules correctly

initial playground update to work with 3.x

---

README.md
docs/api/README.md
docs/api/common/directive.md
docs/api/common/pipe.md
docs/api/core/class.md
docs/api/core/decorator.md
docs/api/core/enum.md
docs/api/core/function.md
docs/api/platform-browser-dynamic/class.md
docs/api/platform-browser-dynamic/function.md
docs/api/router-deprecated/class.md
docs/api/testing/function.md
docs/api/upgrade/class.md
docs/recipes/README.md
docs/recipes/bootstrap.md
docs/recipes/component.md
docs/recipes/constant.md
docs/recipes/deprecated-router.md
docs/recipes/directive.md
docs/recipes/factory.md
docs/recipes/ng-upgrade.md
docs/recipes/pipe.md
docs/recipes/service.md
docs/recipes/startup-logic.md
docs/recipes/ui-router.md
docs/recipes/value.md
playground/ng-metadata.legacy.d.ts
src/core/di/reflective_provider.ts
test/core/util/bundler.spec.ts

Lots of changes required, so I did every section in individual commits to make it easier to review.
I wasn't super strict about it or anything, but as I was going along I tried to improve some language and whitespace consistency as well.

docs(README, recipes, API): Updated documentation for NgModule

---

docs/api/testing/README.md

Hi,
This is a small fix of typos.
Thank you very much for your project.
This is really awesome.
I converted a project from ng-forward to ng-metadata and the support for ie is really first class.

small fixing of typos

---

CONTRIBUTING.md
README.md
SUMMARY.md
docs/api/upgrade/class.md
docs/api/upgrade/function.md
docs/recipes/ng-upgrade.md
src/upgrade/static/downgrade_component.ts
src/upgrade/static/downgrade_injectable.ts
src/upgrade/static/upgrade_injectable.ts

Upgrade aot docs
